name: check-header

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  check-header:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check copyright headers
        run: python scripts/check_header.py --check
